name: pizda
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test-huyni
        uses: actions/setup-node@v4
      - run: make setup
      - run: make start
      - run: make test
      - run: make lint
